### ISSUE TITLE
can't install this on VS Pro 2017 v.15.9.24

### ISSUE THREAD

**Issue by aczutro** [jendelel/MultiWordHighlight#4]
Hi,
this single extension increases my productivity by 1000 and I really hate to live without it.

However, we upgraded VS at my company today, to the version mentioned above.  I cannot change it, it's company policy.

And I can't install the extension any more, apparently because of a dependency to MPF 16.0.  However, if what I found out is correct, MPF 16.0 comes with VS 2019, while the marketplace description of this extension says 2017 is supported.  And I found no way to install MPF 16.0.

The extension did previously work on an older version of VS Pro 2017.  I installed approx. 6 months ago.

**Comment by jendelel** [comment]
Hi @aczutro, 

I am glad that you like the extension. It was super hard for me to keep the support for all the VS versions, so I think I compiled the latest version with the newest VS only. The easiest for you is to install the older version. There were no other changes added. You can download it from [here](https://github.com/jendelel/MultiWordHighlight/releases/tag/1.0.2). Double clicking the downloaded vsix should do the job. 

Let me know if that helped :)

**Comment by aczutro** [comment]
Hi Lukas,

thank you for your quick response! The version you suggested worked out. Thank you again!

Cheers,

Alexander
--
Alexander Czutro
Dorfstrasse 5
6319 Allenwinden
SWITZERLAND

+41-79-612-6201
